### ISSUE TITLE
Add recaptcha 3 support for anti-spam protection

### ISSUE THREAD

**Issue by cirykpopeye** [sulu/SuluFormBundle#247]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes

#### Actual Behavior

Recaptcha v2 integration if enabled; Spam gets through easily

#### Expected Behavior

update to recaptcha v3 and add honeypot, maybe time-based ( at least 10s on page before submit?)

#### Possible Solutions

I created a bundle already where the honeypot is introduced and the recaptcha is updated to v3.
https://packagist.org/packages/comsa/sulu-spam-free-bundle

What are your thoughts?

**Comment by alexander-schranz** [comment]
@cirykpopeye the SuluFormBundle comes with a honeypot field it just need to be activated see: https://github.com/sulu/SuluFormBundle/blob/master/Resources/doc/dynamic.md#add-honeypot-field-for-spam-protection. We use the honeypot on sulu website and since implemented we have 0 spam.

The recaptcha currently is currently not provided by sulu form bundle it comes from the ewzrecaptchabundle as documented [here](https://github.com/sulu/SuluFormBundle/blob/master/Resources/doc/recaptcha.md):
They sadly have not yet a recaptcha v3 implementation https://github.com/excelwebzone/EWZRecaptchaBundle/issues/218
Maybe there are currently better alternative bundles which we could implement a bridge type to it.

**Comment by alexander-schranz** [comment]
I'm thinking about adding a bridge type to https://github.com/karser/KarserRecaptcha3Bundle. Will Renmae this issue to Recaptcha V3 as the honeypot is implemented.

**Comment by manuxi** [comment]
Since even before the recaptcha v3 integration in EWZRecaptchaBundle is there.

**Comment by alexander-schranz** [comment]
@manuxi thats nice to hear, thank you! So we can close this issue now!
