### ISSUE TITLE
Duplicating form fields removes original field

### ISSUE THREAD

**Issue by jeroenmager1** [sulu/SuluFormBundle#336]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Bundle Version | 2.5
| Sulu Version | 2.5
| Browser Version | Browser name and version

#### Actual Behavior

If you edit a Sulu form in the admin and click on the duplicate button of a form field, it deletes the original version of the form field the moment you hit the save button. 

#### Expected Behavior

I expect that if i duplicate a form field both the original and the newly created form field keep existing after saving.

#### Steps to Reproduce

In a form click on the duplicate button of a form field. Click on the save button

**Comment by 0xJas0n** [comment]
@alexander-schranz This bug occurs because the duplicated block also includes the same `id` and `key` as the original block in the POST request which in turn overrides the original (As shown in this screenshot).

<img width="578" alt="image" src="https://github.com/sulu/SuluFormBundle/assets/29687216/fcbdde93-52d7-4824-aa38-6d6e6de32fab">

I tried removing both fields in the `FormManager.php` inside the `updateFields` method in hopes that it generates the values itself which did NOT work. I think the fields need to be removed before the POST request gets sent.

I would appreciate any updates on this issue.

**Comment by alexander-schranz** [comment]
I think we need adjust here something: https://github.com/sulu/SuluFormBundle/blob/2.5/Manager/FormManager.php#L313

```diff
+        $fields = self::getValue($data, 'fields', []);
+        $existingIds = [];
+        $existingKeys = [];
+        foreach ($fields as &$fieldData) {
+             if (\in_array($field['id'] ?? null, $existingId) {
+                  \unset($field['id']);
+             }
+             if (\in_array($field['key'] ?? null, $existingKeys) {
+                  \unset($field['key']);
+             }
+             
+             if (isset($field['id'])) {
+                 $existingIds[] = $field['id'];
+             }
+             
+             if (isset($field['key'])) {
+                 $existingKeys[] = $field['key'];
+             }
+        }
-        $reservedKeys = \array_column(self::getValue($data, 'fields', []), 'key');
+        $reservedKeys = \array_column($fields, 'key');

        $counter = 0;

-        foreach (self::getValue($data, 'fields', []) as $fieldData) {
+        foreach ($fields as $fieldData) {
```

Then it should be correctly create a new field as `key` does not exist for the copied form field.

**Comment by alexander-schranz** [comment]
@0xJas0n @jeroenmager1  please give https://github.com/sulu/SuluFormBundle/pull/377 a try
